added failing test to exercise GitHub API on device
Fails on my device with NoClassDefFoundError for 'org.apache.a.g.k':

[INFO]     Start: com.github.mobile.android.GitHubApiTest#testRepoApi
[INFO]     ERROR:com.github.mobile.android.GitHubApiTest#testRepoApi
[INFO]     java.lang.ExceptionInInitializerError
at org.eclipse.egit.github.core.service.GitHubService.<init>(SourceFile:43)
at org.eclipse.egit.github.core.service.RepositoryService.<init>(SourceFile:88)
at com.github.mobile.android.GitHubApiTest.testRepoApi(SourceFile:33)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
Caused by: java.lang.NoClassDefFoundError: org.apache.a.g.k
at org.eclipse.egit.github.core.client.GitHubClient.<clinit>(SourceFile:93)
... 15 more